#!/usr/bin/env python3

import argparse
import ast
import json
import logging
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent
DEFAULT_BLUEPRINT_FILE = PROJECT_ROOT / "blueprint.md"
OUTPUT_DIR = PROJECT_ROOT / "output"

AGENT_FILES = {
    "orchestrator": PROJECT_ROOT / "rpg_orchestrator.agent.md",
    "designer": PROJECT_ROOT / "rpg_game_designer.agent.md",
    "engineer": PROJECT_ROOT / "rpg_backend_engineer.agent.md",
}


def parse_args():
    parser = argparse.ArgumentParser(description="Generic multi-file autoprogrammer MVP.")
    parser.add_argument(
        "--blueprint",
        default=str(DEFAULT_BLUEPRINT_FILE),
        help="Path to blueprint/spec markdown file"
    )
    parser.add_argument(
        "--output",
        default=str(OUTPUT_DIR),
        help="Output directory for generated files"
    )
    return parser.parse_args()


def load_text_file(path: Path) -> str:
    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")
    return path.read_text(encoding="utf-8").strip()


def load_agents() -> dict[str, str]:
    agents = {}
    for name, path in AGENT_FILES.items():
        if path.exists():
            agents[name] = load_text_file(path)
            logger.info("Loaded agent: %s", path.name)
        else:
            logger.warning("Agent file not found: %s", path.name)
            agents[name] = ""
    return agents


def validate_python_code(code: str) -> tuple[bool, str]:
    try:
        ast.parse(code)
        return True, ""
    except SyntaxError as e:
        return False, f"SyntaxError: {e}"


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    logger.info("Wrote file: %s", path)


def generate_plan(blueprint: str, agents: dict[str, str]) -> str:
    return (
        "# Project Plan\n\n"
        "## Blueprint Summary\n"
        f"{blueprint}\n\n"
        "## Agent Inputs\n"
        f"- Orchestrator agent loaded: {'yes' if agents.get('orchestrator') else 'no'}\n"
        f"- Designer agent loaded: {'yes' if agents.get('designer') else 'no'}\n"
        f"- Engineer agent loaded: {'yes' if agents.get('engineer') else 'no'}\n\n"
        "## Proposed Output Files\n"
        "- README.md\n"
        "- main.py\n"
        "- utils.py\n\n"
        "## Implementation Notes\n"
        "- Generate a simple multi-file Python project\n"
        "- Keep the code self-contained\n"
        "- Make the structure easy to extend\n"
        "- Prepare for future LLM integration\n"
    )


def generate_file_manifest(blueprint: str, plan: str, agents: dict[str, str]) -> list[dict]:
    return [
        {
            "path": "README.md",
            "type": "markdown",
            "description": "Project overview and usage instructions"
        },
        {
            "path": "main.py",
            "type": "python",
            "description": "Main program entry point"
        },
        {
            "path": "utils.py",
            "type": "python",
            "description": "Utility helpers"
        },
        {
            "path": "plan.json",
            "type": "json",
            "description": "Structured metadata about the generated project"
        }
    ]


def generate_readme(blueprint: str, plan: str) -> str:
    return (
        "# Generated Project\n\n"
        "This project was generated by Autoprogrammer.\n\n"
        "## Original Blueprint\n\n"
        f"{blueprint}\n\n"
        "## Generated Files\n\n"
        "- `main.py`\n"
        "- `utils.py`\n"
        "- `plan.md`\n"
        "- `plan.json`\n\n"
        "## Run\n\n"
        "```bash\n"
        "python main.py\n"
        "```\n\n"
        "## Notes\n\n"
        "This is an MVP output generated from a placeholder pipeline.\n"
    )


def generate_main_py(blueprint: str, plan: str) -> str:
    return (
        "from utils import print_banner\n\n\n"
        "def main():\n"
        '    print_banner("Generated Project")\n'
        '    print("This project was generated by Autoprogrammer.")\n'
        '    print("Edit this file to implement the requested blueprint.")\n\n\n'
        'if __name__ == "__main__":\n'
        "    main()\n"
    )


def generate_utils_py() -> str:
    return (
        "def print_banner(title: str) -> None:\n"
        '    print("=" * 60)\n'
        "    print(title)\n"
        '    print("=" * 60)\n'
    )


def generate_plan_json(blueprint: str, manifest: list[dict]) -> str:
    payload = {
        "blueprint": blueprint,
        "files": manifest,
        "generator": "autoprogrammer-mvp",
        "status": "placeholder"
    }
    return json.dumps(payload, indent=2)


def generate_project_files(blueprint: str, agents: dict[str, str], output_dir: Path) -> None:
    logger.info("Generating project plan...")
    plan = generate_plan(blueprint, agents)

    logger.info("Generating file manifest...")
    manifest = generate_file_manifest(blueprint, plan, agents)

    write_file(output_dir / "plan.md", plan)
    write_file(output_dir / "README.md", generate_readme(blueprint, plan))

    utils_py = generate_utils_py()
    valid, error = validate_python_code(utils_py)
    if not valid:
        raise ValueError(f"Generated utils.py failed validation: {error}")
    write_file(output_dir / "utils.py", utils_py)

    main_py = generate_main_py(blueprint, plan)
    valid, error = validate_python_code(main_py)
    if not valid:
        raise ValueError(f"Generated main.py failed validation: {error}")
    write_file(output_dir / "main.py", main_py)

    write_file(output_dir / "plan.json", generate_plan_json(blueprint, manifest))


def main():
    args = parse_args()
    blueprint_path = Path(args.blueprint)
    output_dir = Path(args.output)

    logger.info("Autoprogrammer MVP Started")
    logger.info("Blueprint file: %s", blueprint_path)
    logger.info("Output directory: %s", output_dir)

    if not blueprint_path.exists():
        logger.error("Missing blueprint file: %s", blueprint_path)
        return

    blueprint = load_text_file(blueprint_path)
    if not blueprint:
        logger.error("Blueprint file is empty: %s", blueprint_path)
        return

    agents = load_agents()
    generate_project_files(blueprint, agents, output_dir)

    logger.info("Done. Generated project written to: %s", output_dir)


if __name__ == "__main__":
    main()